name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  CRATE_IO_TOKEN: ${{ secrets.CRATE_IO_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      pr: ${{ steps.release.outputs.pr }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - id: release
        name: Release
        uses: googleapis/release-please-action@v4.2.0
        with:
          release-type: rust
  build-publish:
    runs-on: ubuntu-latest
    name: Build & publish
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - id: checkout-code
        uses: actions/checkout@v4.2.2
      - id: setup-rust
        uses: nebetoxyz/setup-rust--action@v1.2.0
        with:
          cache: cargo
      - id: setup-dependencies
        name: Setup dependencies
        run: cargo install
      - id: build-code
        name: Build code
        run: cargo build --release --timings
      - id: publish-code
        name: Publish code on crates.io
        run: cargo publish --dry-run --token ${{ env.CRATE_IO_TOKEN }}
